"""add claims table

Revision ID: 596e6539af2a
Revises: 3a8758ffa2b0
Create Date: 2026-04-01 17:17:42.208685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '596e6539af2a'
down_revision: Union[str, None] = '3a8758ffa2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_document_id'), 'claims', ['document_id'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_document_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
